llm_groq:
  model: 'llama3-70B-8192'
  api_key: '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'

qdrant:
  url: 'https://618dc965-c6d2-4c3b-93bd-26050204f910.us-east4-0.gcp.cloud.qdrant.io:6333'
  api_key: 'AVW6PnZn-3ld6bw33exaLaohJd8JymLDne4Mk4nIE298dhtB_XS5hQ'
  collection_name: 'healt_care'
  dense_embedding: 'sentence-transformers/all-MiniLM-L6-v2'
  sparse_embedding: 'Qdrant/bm25'
  late_interaction_embedding: 'colbert-ir/colbertv2.0'
  batch_size: 2
  thresh_score: 0.6